apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-app
  labels:
    app: configuration-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-app
  template:
    metadata:
      labels:
        app: configuration-app
    spec:
      containers:
        - name: configuration-app
          image: yesswaroop/configuration:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  ports:
    - targetPort: 9296
      port: 80
  selector:
    app: configuration-app
