apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-app
  labels:
    app: department-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-app
  template:
    metadata:
      labels:
        app: department-app
    spec:
      containers:
        - name: department-app
          image: yesswaroop/department:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: department-app
