apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: yesswaroop/user:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: user-app
